from mysqlrep import Server, User, Linux

servers = [Server(server_id=1,
                  sql_user=User("mysql_replicant", "xyzzy"),
                  ssh_user=User("mats"),
                  machine=Linux(),
                  port=3307,
                  socket='/var/run/mysqld/mysqld1.sock',
                  config_path='/etc/mysql/mysqld1.cnf',
                  config_section='mysqld1'),
           Server(server_id=2,
                  sql_user=User("mysql_replicant", "xyzzy"),
                  ssh_user=User("mats"),
                  machine=Linux(),
                  port=3308,
                  socket='/var/run/mysqld/mysqld2.sock',
                  config_path='/etc/mysql/mysqld2.cnf',
                  config_section='mysqld2'),
           Server(sql_user=User("mysql_replicant", "xyzzy"),
                  ssh_user=User("mats"),
                  machine=Linux(),
                  port=3309,
                  socket='/var/run/mysqld/mysqld3.sock',
                  config_path='/etc/mysql/mysqld3.cnf',
                  config_section='mysqld3'),
           Server(sql_user=User("mysql_replicant", "xyzzy"),
                  ssh_user=User("mats"),
                  machine=Linux(),
                  port=3310,
                  socket='/var/run/mysqld/mysqld4.sock',
                  config_path='/etc/mysql/mysqld4.cnf',
                  config_section='mysqld4')]
master = servers[0]
slaves = servers[1:]
